### ISSUE TITLE
Still have issue with redirection not happening on session expiration

### ISSUE THREAD

**Issue by julienV** [marmelab/ra-auth-cognito#5]
see #3

**Comment by djhi** [comment]
I can't reproduce this issue. Can you provide a reproduction?

**Comment by julienV** [comment]
i don't see it any more either, maybe an issue with cache on my side, let's close it...

**Comment by doerfli** [comment]
i still see the issue as its not included in version 1.0.1. Do you plan to release a new version that includes the fix?

**Comment by julienV** [comment]
please can you make a new release with the fix... it's in fact not in 1.0.1
![image](https://github.com/marmelab/ra-auth-cognito/assets/169588/1e5c290f-ad67-4735-8235-6effe9101e1b)

**Comment by djhi** [comment]
Version 1.0.2 has been published
