### ISSUE TITLE
Feature request: an easier way to access to cognito tokens

### ISSUE THREAD

**Issue by betimer** [marmelab/ra-auth-cognito#9]
The current work around (https://github.com/marmelab/ra-auth-cognito/issues/6) is not approprite.

Would there be an easier way to access accessTokens or IdTokens for cognito user?

Thanks.

**Comment by djhi** [comment]
Why is it not appropriate?

**Comment by betimer** [comment]
@djhi I am still checking if any convenient method e.g. CognitoAuthProvider.getTokens which returns current user's token, instead of going all from cognito native code.

If you already know some work around, please share. much appreciate.

**Comment by djhi** [comment]
You didn't answer my question

**Comment by betimer** [comment]
@djhi That's fine. I have checked all the source code of ra-auth-cognito, which does not provide this built-in handy function. I just made a decision to directly go with react instead of react-admin, with other considerations as well.

Thank you for the reply anyway, mate.

**Comment by abanobmikaeel** [comment]
If we can automatically inject the jwt we get into all requests used by Data Providers, would be pretty nice

**Comment by djhi** [comment]
Some dataProviders support setting the httpClient for this purpose. See https://marmelab.com/react-admin/fetchJson.html
